# Generated by Django 2.2 on 2020-03-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateField(),
        ),
    ]
